apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-stack-grafana
  namespace: default  # Ajusta el namespace si es necesario
data:
  grafana.ini: |
    [server]
    domain = ''
    root_url = "%(protocol)s://%(domain)s/monitoring"
    serve_from_sub_path = true

    # Aquí puedes agregar más configuraciones si es necesario.
    # Asegúrate de incluir todas las configuraciones personalizadas que Grafana pueda necesitar.

  # Si necesitas otros archivos como dashboards o datasources, puedes agregarlos aquí también
  # dashboards.yaml: |
  #   ...
  # datasources.yaml: |
  #   ...
