apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expensy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # Reescribe solo para rutas que lo necesiten
    nginx.ingress.kubernetes.io/use-regex: "true" # Permite usar expresiones regulares en las rutas
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Frontend
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: expensy-frontend
                port:
                  number: 80
          # Backend (sin reescritura)
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: expensy-backend
                port:
                  number: 8706
          # Grafana (sin reescritura)
          - path: /monitoring(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: monitoring-stack-grafana
                port:
                  number: 80