name: Deploy containers with Helm

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to ACR"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          method: service-principal
          cluster-name: ironhack-final-aks
          resource-group: ironhack-final-rg
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Install NGINX Ingress Controller
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx --create-namespace

      - name: Wait for Ingress Controller
        run: |
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=120s

      - name: Deploy Application
        run: |
          helm upgrade --install ironhack-final ./deployment/ironhack-final --wait

      - name: Get Ingress IP
        run: |
          kubectl get svc -n ingress-nginx ingress-nginx-controller