name: Deploy containers with Helm

on:
  workflow_run:
    workflows: ["Build and Push Docker Image to ACR"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NGINX Ingress Controller
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace
      
      - name: Install Application
        run: |
          helm install ironhack-final ./deployment/ironhack-final
  