name: Deploy Monitoring Stack

on:
    workflow_run:
      workflows: ["Deploy AKS"]
      types:
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Add Helm repository
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Deploy Prometheus & Grafana
        run: |
          helm upgrade --install monitoring-stack prometheus-community/kube-prometheus-stack \
            --namespace monitoring --create-namespace \
            --set grafana.adminPassword=${{ secrets.GRAFANA_PASSWORD }}

      - name: Wait for pods to be ready
        run: |
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=grafana -n monitoring --timeout=300s
          kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=prometheus -n monitoring --timeout=300s

      - name: Verify deployment
        run: kubectl get pods -n monitoring